import 'package:class_open/classes/subject.dart';

extension InitializeSubject on Subject {
  static Set<Subject> initialList() {
    final instances = <Subject>{};
    _subjects.forEach((key, value) {
      instances.add(Subject(key, value));
    });
    return instances;
  }
}

Map<String, String> _subjects = {
  'ACCT': 'Accounting',
  'ACDM': 'Acedeum',
  'ANTH': 'Anthropology',
  'ARAB': 'Arabic',
  'ART': 'Art',
  'AUTO': 'Automotive',
  'AVIA': 'Aviation',
  'BIOL': 'Biology',
  'BUAD': 'Business Administration',
  'CDEV': 'Career Development',
  'CHEM': 'Chemistry',
  'CIS': 'Computer Information Systems',
  'COMM': 'Communications',
  'CORR': 'Corr: Law Enf and Crim Justice',
  'CPTR': 'Computer Science',
  'CYBS': 'Cybersecurity',
  'DRMA': 'Drama',
  'DSGN': 'Design',
  'ECON': 'Economics',
  'EDAD': 'Educational Administration',
  'EDCI': 'Education Curriculum & Instruc',
  'EDFB': 'Education Field Based',
  'EDUC': 'Education',
  'ENGL': 'English',
  'ENGR': 'Engineering',
  'ENVI': 'Environmental Studies',
  'FILM': 'Film',
  'FINA': 'Finance',
  'FLTV': 'Film and Television',
  'FREN': 'French',
  'GBUS': 'General Business',
  'GCDP': 'Global Community Development Program',
  'GDEV': 'Game Development',
  'GEOG': 'World Geography',
  'GNRL': 'General',
  'GREK': 'Greek',
  'GRMN': 'German',
  'GRPH': 'Graphics',
  'HEBR': 'Hebrew',
  'HIST': 'History',
  'HLTH': 'Health',
  'HMEC': 'Home Economics',
  'HMNT': 'Humanities (HMNT)',
  'HONR': 'Honors',
  'HUMN': 'Humanities (HUMN)',
  'ILL': 'Illustration',
  'INDS': 'Industrial Design',
  'INFO': 'Informational Technology',
  'ITLN': 'Italian',
  'JOUR': 'Journalism',
  'LAFS': 'LA Film Studies',
  'LANG': 'Language',
  'LATN': 'Latin',
  'LAW': 'Law',
  'MATH': 'Mathematics',
  'MDEV': 'Developmental Mathematics',
  'MDLG': 'Modern Language',
  'MEDU': 'Mathematics Education',
  'MGMT': 'Management',
  'MKTG': 'Marketing',
  'MUCT': 'Composition and Theory',
  'MUED': 'Music Education',
  'MUHL': 'Music History and Literature',
  'MUPF': 'Music Performance',
  'NRSG': 'Nursing',
  'OXFD': 'Oxford Classes',
  'PEAC': 'Physical Activity Courses',
  'PETH': 'Physical Education Theory',
  'PHIL': 'Philosophy',
  'PHTO': 'Photography',
  'PHYS': 'Physics',
  'PLSC': 'Political Science',
  'PORT': 'Portuguese',
  'PRDN': 'Product Design',
  'PREL': 'Public Relations',
  'PSYC': 'Psychology',
  'RELB': 'Biblical Studies',
  'RELG': 'General Religion',
  'RELH': 'Religious History',
  'RELI': 'Ministry & Evangelism',
  'RELM': 'Missions',
  'RELP': 'Professional',
  'RELT': 'Theology',
  'SCDI': 'Scientific Diving',
  'SERV': 'Service Learning',
  'SMTF': 'Student Missionary Task Force',
  'SOCI': 'Sociology',
  'SOWK': 'Social Work',
  'SPAN': 'Spanish',
  'SPCH': 'Speech',
  'SPED': 'Special Education',
  'SPPA': 'Speech-Language Path and Audio',
  'TECH': 'Technology Education',
  'WHIT': 'Whitman Course',
  'WRIT': 'Writing',
};
